## FEIGN Configuration
feign:
  retry:
    period: 2000
    maxPeriod: 5000
    maxAttempts: 2
  client:
    config:
      default:
        connectTimeout: 7000
        readTimeout: 7000

## CHAOS Configurations
chaos:
  monkey:  
    enabled: true
    watcher:
      controller: true
      repository: true
      rest-controller: true
      service: true
    assaults:
      level: 2
      latencyRangeStart: 5000
      latencyRangeEnd: 10000
      latencyActive: true
      exceptionsActive: true
      killApplicationActive: false
      
 ## ACTUATOR configs
 ## Actuator
management:
  endpoint:
    chaosmonkey.enabled: true
    chaosmonkeyjmx.enabled: true
    metrics.enabled: true
