spring:
  jpa:
    hibernate:
      ddl-auto=create
  datasource:
    url: jdbc:mysql:localhost:3306/ARTISTSDB
    username: root
    password: password

external:
  services:
    songs: musiclab-songs
    version: 2021-01
